#!/bin/bash
source $(dirname $0)/check.sh
source $(dirname $0)/incl.sh

homedir=$1
user=$2

if [ $1 != $homedir ]; then
  echo "$1 != $homedir, stopping script to prevent damage."
  exit 1
fi

if [ $2 != $user ]; then
  echo "$2 != $user, stopping script to prevent damage."
  exit 1
fi

# Installing dependencies
apt-get -y install subversion build-essential automake libtool screen curl libcppunit-dev libcurl3-dev libsigc++-2.0-dev libncurses-dev libcurl4-openssl-dev libcppunit-dev libncurses5-dev libsigc++-2.0-dev

if [ ! -f /usr/local/bin/rtorrent ]; then # Is rtorrent already installed (START)
# Installing xmlrpc-c
svn checkout http://svn.code.sf.net/p/xmlrpc-c/code/stable xmlrpc-c
cd xmlrpc-c
./configure --disable-cplusplus
make
make install
cd ..
rm -rf xmlrpc-c

mkdir rtorrent
cd rtorrent

# Installing libtorrent.
wget http://libtorrent.rakshasa.no/downloads/libtorrent-0.13.4.tar.gz
tar -zxvf libtorrent-0.13.4.tar.gz
cd libtorrent-0.13.4
./autogen.sh
./configure
make
make install
cd ..

# Installing rtorrent.
wget http://libtorrent.rakshasa.no/downloads/rtorrent-0.9.4.tar.gz
tar -zxvf rtorrent-0.9.4.tar.gz
cd rtorrent-0.9.4
./autogen.sh
./configure --with-xmlrpc-c
make
make install
cd ../..
rm -rf rtorrent

ldconfig
echo "rTorrent installed successfully." >> output.txt
else
	echo "rTorrent is already installed." >> output.txt
fi # Is rtorrent already installed (END)

# Creating session directory
if [ ! -d "$homedir"/.rtorrent-session ]; then
	mkdir "$homedir"/.rtorrent-session
	chown "$user"."$user" "$homedir"/.rtorrent-session
else
	chown "$user"."$user" "$homedir"/.rtorrent-session
fi

# Creating downloads folder
if [ ! -d "$homedir"/Downloads ]; then
	mkdir "$homedir"/Downloads
	chown "$user"."$user" "$homedir"/Downloads
else
	chown "$user"."$user" "$homedir"/Downloads
fi

# Creating watch folder
if [ ! -d "$homedir"/watch ]; then
	mkdir "$homedir"/watch
	chown "$user"."$user" "$homedir"/watch
else
	chown "$user"."$user" "$homedir"/watch
fi

# Downloading rtorrent.rc file.
#wget --no-check-certificate -O $homedir/.rtorrent.rc https://raw.githubusercontent.com/igrewup/rtorrent/master/.rtorrent.rc
cp .rtorrent.rc $homedir/.rtorrent.rc
chown "$user"."$user" $homedir/.rtorrent.rc
sed -i "s@HOMEDIRHERE@$homedir@g" $homedir/.rtorrent.rc


# Downloading and installing rtorrent init script.
if [ ! -f /etc/init.d/rtorrent-init ]; then
#wget --no-check-certificate -O /etc/init.d/rtorrent-init https://raw.githubusercontent.com/igrewup/rtorrent/master/rtorrent-init
cp rtorrent-init /etc/init.d/ && chmod +x /etc/init.d/rtorrent-init
sed -i "s/USERNAMEHERE/$user/g" /etc/init.d/rtorrent-init
update-rc.d rtorrent-init defaults
fi

service rtorrent-init start

echo "rTorrent settings updated sucessfully." >> output.txt
