#!/bin/bash
source $(dirname $0)/check.sh
source $(dirname $0)/incl.sh

# Installing dependencies
apt-get -y install subversion openssl git-core apache2 apache2-utils build-essential libsigc++-2.0-dev \
libcurl4-openssl-dev automake libtool libcppunit-dev libncurses5-dev libapache2-mod-scgi \
php5 php5-curl php5-cli libapache2-mod-php5 screen unzip unrar-free libssl-dev curl ffmpeg mediainfo

# Installing rutorrent.
cd /var/www
git clone git://github.com/Novik/ruTorrent.git

sed -i 's/newTitle+=".*;/newTitle+="ruTor";/' /var/www/rutor/js/webui.js

# Changeing permissions for rutorrent and plugins.
chown -R www-data.www-data /var/www/rutor
chmod -R 775 /var/www/rutor/
cp .htaccess /var/www/rutor/
chmod 444 /var/www/rutor/.htaccess

if [ ! -f /etc/apache2/.htpasswd ]; then
# Creating user for webinterface.
echo -n "Please type the username for the webinterface, system user not required: "
read -e htauser

while true; do
	htpasswd -c /etc/apache2/.htpasswd "$htauser"
	if [ $? = 0 ]; then
		break
	fi
done
fi
chmod 444 /etc/apache2/.htpasswd

# Creating Apache virtual host
rm /etc/apache2/sites-available/rutor
echo '<VirtualHost *:80>
	ServerName *
	ServerAlias *
        DocumentRoot /var/www/
        CustomLog /var/log/apache2/rutorrent.log vhost_combined
        ErrorLog /var/log/apache2/rutorrent_error.log

        SCGIMount /RPC2 127.0.0.1:5000
        <location /RPC2>
                AuthName "Tits or GTFO"
                AuthType Basic
                Require Valid-User
                AuthUserFile /etc/apache2/.htpasswd
        </location>
</VirtualHost>' > /etc/apache2/sites-available/rutor

# Creating Apache SSL certificates
if [ ! -f /etc/ssl/private/apache.crt ]; then
openssl req -x509 -nodes -days 12000 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -newkey rsa:2048 -keyout /etc/ssl/private/apache.key -out /etc/ssl/private/apache.crt
chmod 600 /etc/ssl/private/apache.*
fi

# Create Apache SSL website
rm /etc/apache2/sites-available/default-ssl
echo '<IfModule mod_ssl.c>
<VirtualHost _default_:443>
	ServerAdmin webmaster@localhost

	DocumentRoot /var/www
	<Directory />
		Options FollowSymLinks
		AllowOverride All
	</Directory>
	<Directory /var/www/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>

	ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
	<Directory "/usr/lib/cgi-bin">
		AllowOverride None
		Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
		Order allow,deny
		Allow from all
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog ${APACHE_LOG_DIR}/ssl_access.log combined

	SSLEngine on

	SSLCertificateFile /etc/ssl/private/apache.crt
	SSLCertificateKeyFile /etc/ssl/private/apache.key

	<FilesMatch "\.(cgi|shtml|phtml|php)$">
		SSLOptions +StdEnvVars
	</FilesMatch>
	<Directory /usr/lib/cgi-bin>
		SSLOptions +StdEnvVars
	</Directory>

	BrowserMatch "MSIE [2-6]" \
		nokeepalive ssl-unclean-shutdown \
		downgrade-1.0 force-response-1.0
	# MSIE 7 and newer should be able to use keepalive
	BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

</VirtualHost>
</IfModule>' > /etc/apache2/sites-available/default-ssl
chmod 644 /etc/apache2/sites-available/*

a2enmod ssl
a2enmod scgi
a2enmod rewrite
a2ensite default-ssl
a2ensite rutor

service apache2 restart

echo "ruTorrent installed successfully." >> $OUTPUTFILE
