#!/bin/bash
source $(dirname $0)/check.sh
source $(dirname $0)/incl.sh

# $1 = $homedir
plugindir="/var/www/rutor/plugins/"

apt-get -y install php5-geoip ffmpeg curl libzen0 libmediainfo0 mediainfo

wget http://dl.bintray.com/novik65/generic/plugins-3.6.tar.gz
tar zxf plugins-3.6.tar.gz -C /var/www/rutor/
	
# UPDATE GEOIP WITH CITIES
wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
gunzip GeoLiteCity.dat.gz
mkdir -v /usr/share/GeoIP
mv -v GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat

# INSTALL FILEMANAGER PLUGIN
rm -f -R /var/www/rutor/plugins/filemanager
cd /var/www/rutor/plugins/
svn co http://svn.rutorrent.org/svn/filemanager/trunk/filemanager
sed -i "$ i\$topDirectory = '$1/';" /var/www/rutor/plugins/filemanager/conf.php

echo "Plugins are installed/updated."  >> $OUTPUTFILE
