#!/bin/bash
source $(dirname $0)/check.sh
source $(dirname $0)/incl.sh

NEWPROXYPORT1=$1

# Start the PROXY setup script.
while :
  do
  if [[ -f /etc/init.d/squid3 ]]; then
  clear
  echo
  echo " Looks like Proxy Server is already installed."
  echo " What do you want to do?"
  echo 
  echo "1) Update Proxy Server"
  echo "2) Remove Proxy Server"
  echo "3) Exit"
  echo 
  read -p " Select an option [1-3]: " option
    case $option in
      1) while :
          do
            echo
            echo " Options available for PROXY SERVER"
            echo "1) Add a new user"
            echo "2) Remove a user"
            echo "3) List current PROXY users"
            echo "4) Update port to $NEWPROXYPORT1"
            echo "5) Update PROXY server config settings"
            echo "6) Back to main menu"
            echo 
            read -p " Select an option [1-6]: " updates
            case $updates in
              1) read -p " Add new PROXY user: " user
              echo
              touch /etc/squid3/passwords
              if grep -wF "$user" /etc/squid3/passwords > /dev/null ; then
                echo " User $user already exist. NOTE: This will overwrite the user's current password."
                $HITENTER
              else
                echo " User doesn't exist."
              fi
              htdigest /etc/squid3/passwords proxy $user
              if grep -wF "$user" /etc/squid3/passwords > /dev/null ; then
                echo " User '$user' created sucessfully." | tee -a $OUTPUTFILE
                check=1
              else
                echo " Error creating '$user'"
              fi
              ;;
              2) read -p " Remove a PROXY user: " user
              if grep -wF "$user" /etc/squid3/passwords > /dev/null ; then
                read -p " Are you sure you want to remove '$user'? (y/n): " REMOVE
                if [ $REMOVE == "y" ]; then
                  sed -i "/\<$user\>/d" /etc/squid3/passwords
                  if grep -wF "$user" /etc/squid3/passwords > /dev/null ; then
                    echo " Error removing '$user'"
                  else
                    echo " User '$user' removed sucessfully." | tee -a $OUTPUTFILE
                  fi
                fi
              else
                echo " User does not exist."
              fi
              ;;
              3) if cat /etc/squid3/passwords > /dev/null ; then
              echo " List of PROXY users."
              cut -d':' -f1 /etc/squid3/passwords
              else
              echo "There are currently no PROXY users."
              fi
              ;;
              4) read -p " Change port to $NEWPROXYPORT1? (y/n): " PORT
              if [ $PORT == "y" ]; then
                cp install_squid_default /etc/squid3/squid.conf
                sed -i "s/http_port.*/http_port $NEWPROXYPORT1/g" /etc/squid3/squid.conf
                echo " Proxy Server Port: $NEWPROXYPORT1" | tee -a $OUTPUTFILE
                service squid3 restart
              fi
              ;;
              5) echo " Update PROXY server config settings" ;;
              6) break ;;
            esac  
          done
      ;;
      2) read -p " Are you sure you want to remove the Proxy Server? (y/n): " REMOVE
      if [ $REMOVE == "y" ]; then
        echo " Removing Proxy Server..." | tee -a $OUTPUTFILE
        apt-get -y purge squid3 && apt-get -y autoremove
        cp /etc/squid3/passwords /etc/squid-passwords.bak
        rm -rf /etc/squid3/
        echo " A backup of your proxy users was created '/etc/squid-passwords.bak'" | tee -a $OUTPUTFILE
        echo " Proxy Server removed successfully." | tee -a $OUTPUTFILE
        $HITENTER
      fi
      ;;
      3) exit;;
    esac

else # Proxy Server is not installed.
  
    clear
    echo
    echo " Looks like Proxy Server is not installed."
    read -p " Do you want to install Proxy Server on port: "$NEWPROXYPORT1" (y/n): " INSTALL
      if [ $INSTALL == "y" ]; then
        echo " Installing Proxy Server..."
        apt-get -y install squid3
        mv /etc/squid3/squid.conf /etc/squid3/squid.conf-orig
        cp install_squid_default /etc/squid3/squid.conf
        sed -i "s/http_port.*/http_port $NEWPROXYPORT1/g" /etc/squid3/squid.conf
        service squid3 restart
        echo " Proxy Server installed successfully" | tee -a $OUTPUTFILE
      else
        echo " Aborting Proxy Server installation" | tee -a $OUTPUTFILE
        $HITENTER
      fi
    fi
    
  done
  
echo " All done!"

# Include footer.sh
source $(dirname $0)/footer.sh
