#!/bin/bash
source $(dirname $0)/check.sh
source $(dirname $0)/incl.sh

homedir=$1
user=$2

if [ $1 != $homedir ]; then
  echo "$1 != $homedir, stopping script to prevent damage."
  exit 1
fi

if [ $2 != $user ]; then
  echo "$2 != $user, stopping script to prevent damage."
  exit 1
fi

# Installing dependencies
	apt-get -y install subversion openssl git apache2 apache2-utils build-essential libsigc++-2.0-dev \
	libcurl4-openssl-dev automake libtool libcppunit-dev libncurses5-dev libapache2-mod-scgi \
	php5 php5-curl php5-cli libapache2-mod-php5 screen unzip unrar-free libssl-dev curl
	
if [ ! -f /usr/local/bin/rtorrent ]; then # Is rtorrent already installed (START)

	# Download and install xmlrpc-c super-stable
	curl -L http://sourceforge.net/projects/xmlrpc-c/files/latest/download -o xmlrpc-c-latest.tgz
	tar zxvf xmlrpc-c-latest.tgz
	mv xmlrpc-c-1.* xmlrpc
	cd xmlrpc
	./configure --disable-cplusplus
	make
	make install

	cd ..
	rm -rv xmlrpc*

	mkdir rtorrent
	cd rtorrent

	# Download and install libtorrent
	curl -L https://github.com/rakshasa/libtorrent/archive/0.13.4.tar.gz -o libtorrent-0.13.4.tar.gz
	tar -zxvf libtorrent-0.13.4.tar.gz
	cd libtorrent-0.13.4
	./autogen.sh
	./configure
	make
	make install

	cd ..

	# Download and install rtorrent
	curl -L https://github.com/rakshasa/rtorrent/archive/0.9.4.tar.gz -o rtorrent-0.9.4.tar.gz
	tar -zxvf rtorrent-0.9.4.tar.gz
	cd rtorrent-0.9.4
	./autogen.sh
	./configure --with-xmlrpc-c
	make
	make install

	cd ../..
	rm -rv rtorrent

	ldconfig

	echo "rTorrent installed successfully." >> $OUTPUTFILE
else
	echo "rTorrent is already installed." >> $OUTPUTFILE
fi # Is rtorrent already installed (END)

# Creating session directory
if [ ! -d "$homedir"/.rtorrent-session ]; then
	mkdir "$homedir"/.rtorrent-session
	chown "$user"."$user" "$homedir"/.rtorrent-session
else
	chown "$user"."$user" "$homedir"/.rtorrent-session
fi

# Creating downloads folder
if [ ! -d "$homedir"/Downloads ]; then
	mkdir "$homedir"/Downloads
	chown "$user"."$user" "$homedir"/Downloads
else
	chown "$user"."$user" "$homedir"/Downloads
fi

# Creating watch folder
if [ ! -d "$homedir"/watch ]; then
	mkdir "$homedir"/watch
	chown "$user"."$user" "$homedir"/watch
else
	chown "$user"."$user" "$homedir"/watch
fi

# Creating incomplete folder
if [ ! -d "$homedir"/incomplete ]; then
	mkdir "$homedir"/incomplete
	chown "$user"."$user" "$homedir"/incomplete
else
	chown "$user"."$user" "$homedir"/incomplete
fi

# Downloading rtorrent.rc file.
cp .rtorrent.rc $homedir/.rtorrent.rc
chown "$user"."$user" $homedir/.rtorrent.rc
sed -i "s@HOMEDIRHERE@$homedir@g" $homedir/.rtorrent.rc

# Downloading and installing rtorrent init script.
if [ ! -f /etc/init.d/rtorrent-init ]; then
cp rtorrent-init /etc/init.d/ && chmod +x /etc/init.d/rtorrent-init
sed -i "s/USERNAMEHERE/$user/g" /etc/init.d/rtorrent-init
update-rc.d rtorrent-init defaults
fi

service rtorrent-init start

echo "rTorrent settings updated sucessfully." >> $OUTPUTFILE
