#!/bin/bash
source $(dirname $0)/check.sh
source $(dirname $0)/incl.sh

# Check to make sure the username/password are set.
if [ -z "$3" ]; then
echo "Unable to continue, missing USERNAME variable."
echo "Hit ENTER to exit."
$HITENTER
exit 0;
elif [ -z "$4" ]; then
echo "Unable to continue, missing PASSWORD variable."
echo "Hit ENTER to exit."
$HITENTER
exit 0;
else
echo "User and Password set, Good to go!" 
fi

# Installing dependencies
apt-get -y install subversion openssl git-core apache2 apache2-utils build-essential libsigc++-2.0-dev \
libcurl4-openssl-dev automake libtool libcppunit-dev libncurses5-dev libapache2-mod-scgi \
php5 php5-curl php5-cli libapache2-mod-php5 screen unzip unrar-free libssl-dev curl ffmpeg mediainfo \
libapache2-mod-geoip php5-geoip

if [ ! -f $(dirname $0)/rar_4.0.b3-1_amd64.deb ]; then
wget http://ftp.debian.org/debian/pool/non-free/r/rar/rar_4.0.b3-1_amd64.deb -P $(dirname $0)/
fi
dpkg -i $(dirname $0)/rar_4.0.b3-1_amd64.deb

# Installing rutorrent.
cd /var/www
rm -rf /var/www/rutor/
git clone git://github.com/Novik/ruTorrent.git
mv ruTorrent rutor
sed -i 's/newTitle+=".*;/newTitle+="ruTor";/' /var/www/rutor/js/webui.js
sed -i "s#topDirectory =.*#topDirectory = '~/';#g" /var/www/rutor/conf/config.php

# Creating user for webinterface.
htpasswd -c -b /etc/apache2/.htpasswd $3 $4

# Changeing permissions for rutorrent and plugins.
chown -R www-data.www-data /var/www/rutor
chmod -R 775 /var/www/rutor/
cp /root/rtorrent/.htaccess /var/www/rutor/
chmod 444 /var/www/rutor/.htaccess /etc/apache2/.htpasswd

# Creating Apache virtual host
rm /etc/apache2/sites-available/rutor
echo '<VirtualHost *:80>
	ServerName *
	ServerAlias *
        DocumentRoot /var/www/
        CustomLog /var/log/apache2/rutorrent.log vhost_combined
        ErrorLog /var/log/apache2/rutorrent_error.log

        SCGIMount /RPC2 127.0.0.1:5000
        <location /RPC2>
                AuthName "Tits or GTFO"
                AuthType Basic
                Require Valid-User
                AuthUserFile /etc/apache2/.htpasswd
        </location>
</VirtualHost>' > /etc/apache2/sites-available/rutor

# Creating Apache SSL certificates
if [ ! -f /etc/ssl/private/apache.crt ]; then
openssl req -x509 -nodes -days 12000 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -newkey rsa:2048 -keyout /etc/ssl/private/apache.key -out /etc/ssl/private/apache.crt
chmod 600 /etc/ssl/private/apache.*
fi

# Create Apache SSL website
rm /etc/apache2/sites-available/default-ssl
echo '<IfModule mod_ssl.c>
<VirtualHost _default_:443>
	ServerAdmin webmaster@localhost

	DocumentRoot /var/www
	<Directory />
		Options FollowSymLinks
		AllowOverride All
	</Directory>
	<Directory /var/www/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>

	ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
	<Directory "/usr/lib/cgi-bin">
		AllowOverride None
		Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
		Order allow,deny
		Allow from all
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog ${APACHE_LOG_DIR}/ssl_access.log combined

	SSLEngine on

	SSLCertificateFile /etc/ssl/private/apache.crt
	SSLCertificateKeyFile /etc/ssl/private/apache.key

	<FilesMatch "\.(cgi|shtml|phtml|php)$">
		SSLOptions +StdEnvVars
	</FilesMatch>
	<Directory /usr/lib/cgi-bin>
		SSLOptions +StdEnvVars
	</Directory>

	BrowserMatch "MSIE [2-6]" \
		nokeepalive ssl-unclean-shutdown \
		downgrade-1.0 force-response-1.0
	# MSIE 7 and newer should be able to use keepalive
	BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

</VirtualHost>
</IfModule>' > /etc/apache2/sites-available/default-ssl
chmod 644 /etc/apache2/sites-available/*

# UPDATE GEOIP WITH CITIES
wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
gunzip GeoLiteCity.dat.gz
mkdir -v /usr/share/GeoIP
rm -rf /usr/share/GeoIP/*
mv -v GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat
ln -s /usr/share/GeoIP/GeoIPCity.dat /usr/share/GeoIP/GeoIP.dat
#remove hashtag in file
sed -i "s/  #//g" /etc/apache2/mods-available/geoip.conf

# INSTALL FILEMANAGER PLUGIN
rm -f -R /var/www/rutor/plugins/filemanager
cd /var/www/rutor/plugins/
svn co http://svn.rutorrent.org/svn/filemanager/trunk/filemanager
#sed -i "$ i\$topDirectory = '$1/';" /var/www/rutor/plugins/filemanager/conf.php

echo "Plugins are installed/updated."  >> $OUTPUTFILE

a2enmod ssl
a2enmod scgi
a2enmod geoip
a2enmod rewrite
a2ensite default-ssl
a2ensite rutor

service rtorrent-init restart
service apache2 restart

echo "ruTorrent installed successfully." >> $OUTPUTFILE
