#!/bin/bash
source $(dirname $0)/check.sh
source $(dirname $0)/incl.sh

if [ ! -f /etc/init.d/vsftpd ]; then
	if [ "$OS1" = "Debian" ]; then
		apt-get update
		apt-get install vsftpd
		echo "VSFTPD successfully installed."  >> output.txt
	else
		echo "You are not using Debian. Cannot install VSFTPD."  >> output.txt
	fi
else
	echo "VSFTPD is already installed."  >> output.txt
fi

NEWFTPPORT1=$1
# Create SSL certificate for VSFTPD.
if [ ! -f /etc/ssl/private/vsftpd.pem ]; then
openssl req -x509 -nodes -days 12000 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -newkey rsa:4096 -keyout /etc/ssl/private/vsftpd.key -out /etc/ssl/private/vsftpd.pem
chmod 600 /etc/ssl/private/vsftpd.*
fi

echo "New VSFTPD port: $NEWFTPPORT1"
read -p "Do you want to update VSFTPD settings? (y/n): " UPDATE
echo
if [ "$UPDATE" == "y" ]; then
echo "listen=YES
listen_port=$NEWFTPPORT1
local_root=/home
anonymous_enable=NO
local_enable=YES
write_enable=YES
anon_upload_enable=NO
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=NO
ftpd_banner=Welcome to FTP service.
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
rsa_cert_file=/etc/ssl/private/vsftpd.pem
rsa_private_key_file=/etc/ssl/private/vsftpd.key
local_umask=022
ssl_enable=YES
allow_anon_ssl=NO
force_local_data_ssl=YES
force_local_logins_ssl=YES
ssl_tlsv1=YES
ssl_sslv2=NO
ssl_sslv3=NO
ssl_ciphers=HIGH" > /etc/vsftpd.conf
service vsftpd restart
fi
