#!/bin/bash
source $(dirname $0)/check.sh
source $(dirname $0)/incl.sh

WEBMINPORT1=$1

if [ ! -f /etc/init.d/webmin ]; then
	#if webmin isup, download key
	WEBMINDOWN=YES
	ping -c1 -w2 www.webmin.com > /dev/null
	if [ $? = 0 ] ; then
		WEBMINDOWN=NO
		echo "Webmin server seems up, going to download key and install webmin now."
		wget -O /tmp/webmin.asc http://www.webmin.com/jcameron-key.asc | sudo apt-key add /tmp/webmin.asc
		echo 'deb http://download.webmin.com/download/repository sarge contrib
		deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib' > /etc/apt/sources.list.d/webmin.list
		apt-get update
		apt-get -y install webmin
		rm /tmp/webmin.asc
		echo "Webmin installed successfully."  >> output.txt
	else
		WEBMINDOWN=YES
		echo "Cannot install Webmin, the webserver seems to be down."  >> output.txt
  	fi

else
	echo "Webmin is already installed." >> output.txt
	echo "Webmin port: $WEBMINPORT1" >> output.txt
fi
